### ISSUE TITLE
bluetooth auto on

### ISSUE THREAD

**Issue by prvn93** [elementary/switchboard-plug-bluetooth#107]
Bluetooth is turning on automatically after resuming from suspend.

**Comment by ivcosla** [comment]
I'm having the same issue. Could upload any report in case this is happening only in some specific hardware.

**Comment by NathanBnm** [comment]
I have the same issue. See here too: https://github.com/elementary/switchboard-plug-bluetooth/issues/21

**Comment by ryonakano** [comment]
Closing as a duplicate of #21
