### ISSUE TITLE
Bluetooth Setting and indicator missing on fresh install EOS Hera

### ISSUE THREAD

**Issue by alfianhanafi** [elementary/switchboard-plug-bluetooth#108]
I just install Elementary OS Hera and i dont find Bluetooth setting and BT Indicator

**Setting**
![image](https://user-images.githubusercontent.com/54639904/73164663-f0097080-4124-11ea-9362-5dbe4bd8876c.png)

**Indicator**
![image](https://user-images.githubusercontent.com/54639904/73164745-19c29780-4125-11ea-8712-8294785b7b3c.png)

Please Help

**Comment by tintou** [comment]
Do you have a bluetooth adapter included in your computer, is it disabled using an hardware switch?

**Comment by alfianhanafi** [comment]
> Do you have a bluetooth adapter included in your computer, is it disabled using an hardware switch?

I think not, i mean my wifi is fine.
it has the same button for wifi and Bluetooth (ALT+F2).

im using Asus laptop BTW
when i install Juno it's working properly

**Comment by alfianhanafi** [comment]
my BT status

![image](https://user-images.githubusercontent.com/54639904/73165820-1e884b00-4127-11ea-8bde-fffd3417a0a0.png)
