### ISSUE TITLE
bluetooth not working EOS hera

### ISSUE THREAD

**Issue by amritRomana** [elementary/switchboard-plug-bluetooth#114]
i just installed EOS Hera, after a few days its bluetooth stopped working and moreover tapping the bluetooth icon hangs the whole system, i want a proper solution to that or else i am gonna switch back to windows

**Comment by daniladyabin** [comment]
1. Noone holds you back to use elementary. Do whatever you want.
2. Can you describe the issue better, aka logs, behavior, installed packages, hardware?

**Comment by danirabbit** [comment]
Closing since this is a quite old report and OP never providing additional information
