### ISSUE TITLE
Don't work bluetooth

### ISSUE THREAD

**Issue by Alllgator343** [elementary/switchboard-plug-bluetooth#116]
Hello! I turn on bluetooth, but can't find any devices. After enter "rfkill unblock bluetooth" in the terminal I can find my phone, but can't accept files. Maybe it's because I don't have the option "receive files in downloads folder over bluetooth" in the section "personal file sharing".

Information about my system:

Notebook Lenovo IdeaPad L340-15API
No LSB modules are available.
Distributor ID: elementary
Description: elementary OS 5.1.2 Hera
Release: 5.1.2
Codename: hera
Linux 5.3.0-28-generic
![Снимок экрана от 2020-03-31 21-37-26](https://user-images.githubusercontent.com/39007688/78052018-f7086580-7397-11ea-8430-aa62fab134f2.png)

**Comment by danirabbit** [comment]
Closing because bluetooth file sharing was implemented in a later release
