### ISSUE TITLE
Unpair button isn’t obvious

### ISSUE THREAD

**Issue by gersonjunior87** [elementary/switchboard-plug-bluetooth#131]
I looked for a button to unpair a device that was not connecting correctly and I couldn't find it. I removed it via terminal. It would be interesting to have an unpair button in the device's bluetooth settings.

**Comment by danrabbit** [comment]
There is a “-“ button on the toolbar for unpairing. Admittedly it is very understated. This isn’t the first we’ve heard that it is unclear.

**Comment by rafaelcorsi** [comment]
@danrabbit working on this, i`ve two solutions:

1. Improve visibility on the actual button:

![image](https://user-images.githubusercontent.com/1039615/87214352-0a658e00-c302-11ea-820b-f215972d111e.png)

2. add a individual button to each connection:

![image](https://user-images.githubusercontent.com/1039615/87214303-aba01480-c301-11ea-86a6-1449523d1b8d.png)

**Comment by gersonjunior87** [comment]
Wow, I loved the second choice (but the footer button need be removed, right?)

**Comment by danrabbit** [comment]
@rafaelcorsi Thanks for looking into this! I agree that option 2  (with buttons on each row) is probably the most obvious. And like @gersonjunior87 mentioned, we can then remove the button from the toolbar below.

**Comment by rafaelcorsi** [comment]
@danrabbit ive implemented de seccond option, but I think I have a better solution. 

The idea is to add popover button to all bluetooth devices (not to only that the have a configuration), and on this new window add the option to Forget and Settings plus some information as: 

- Device address (actually is a tooltip)
- Date of last time user connect to device (I dont know if bluz has this information)
- Baterry (is this redundant to the wingpanel indicator?)
- Forget / Settings buttons ( the settings button only appear on some devices)

![image](https://user-images.githubusercontent.com/1039615/87356984-78e06100-c539-11ea-9345-affeea107d04.png)

I was inspired on the wifi settings:

![image](https://user-images.githubusercontent.com/1039615/87357131-be9d2980-c539-11ea-823e-4b68bc740fed.png)

I would like to know if you think it is worth spending more energy on this other idea? Or I send or PR option 2?

**Comment by scottjenson** [comment]
If you don't mind a new comer chiming in... I'm not up to speed on your style guide but the unpair button, while dangerous isn't very common. We should be making it more visible yes, but having all of those red buttons is a bit in-the-users face. It might help to have a clear, but more understated option.

As to the pop up menu, that clearly offers lots more help but it suffers from being *just* that much more hidden. It risks being as hard to find as the original "-" button. Here is a quick mock up but likely I said, I'm new here so if there is a better style guide to follow (e.g. having borders on all your buttons) please let me know
![Trashcan icon](https://user-images.githubusercontent.com/1055674/87886922-9bf58f80-c9d5-11ea-8fd6-51d225415429.png)

**Comment by danrabbit** [comment]
@rafaelcorsi I'm not sure I'm convinced we need a whole menu here, but in any case it would probably be better to save that proposal for another pull request.

I would be interested in @scottjenson's solution of using an image button here. I agree that this is probably not a very common action and so deemphasizing it would be good

If you do decide to go with an image button, remember that image buttons need tooltips :)
