### ISSUE TITLE
bluetooth turn on automatically and cant be disabled

### ISSUE THREAD

**Issue by pepis2** [elementary/switchboard-plug-bluetooth#134]
The bluetooth device turn on automatically all the time and cant be disabled, I don't want to have bluetooth enabled, I never use it and is a security issue if it turn on by itself all the time. I want it to be disabled and keep disabled until I say otherwise

**Comment by jeremypw** [comment]
I think this is essentially  the same as #21 and #130?  I think it is fixed in the unstable distro due to 7281f02aa1fac0463cd012f222767fa7c02b761a.  When this is released, your personal bluetooth settings should not be overridden by the global setting every time you log in.
