### ISSUE TITLE
System settings crashes when trying to open bluetooth menu

### ISSUE THREAD

**Issue by LrdVnz** [elementary/switchboard-plug-bluetooth#136]
The system settings app exits immediately when I try to enter the bluetooth menu. 
I have a Lenovo-B590
Dual Core Intel® Core™ i3-2348M CPU @ 2.30GHz
Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)

**Comment by danirabbit** [comment]
Closing since this is an old report with no logs or terminal output and I can't reproduce
