### ISSUE TITLE
Put discovering status in overlay bar

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-bluetooth#148]
The "discovering" label doesn't need a full length actionbar:

![Screenshot from 2020-10-08 11 37 06@2x](https://user-images.githubusercontent.com/7277719/95499791-a8491300-095a-11eb-836b-9bcf92aeaad3.png)

We can use Granite.Overlaybar for something less intrusive: https://valadoc.org/granite/Granite.Widgets.OverlayBar.html

**Comment by davidmhewitt** [comment]
Fixed in #149
