### ISSUE TITLE
The "Bluetooth Device Search" window does not open expanded

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/switchboard-plug-bluetooth#15]
The "Bluetooth Device Search" window does not open expanded, every time you have to resize the window.
![captura de tela de 2017-05-03 12-30-01](https://cloud.githubusercontent.com/assets/8754997/25668302/b920dc02-2ffc-11e7-813d-bbae142acd62.png)
![captura de tela de 2017-05-03 12-30-16](https://cloud.githubusercontent.com/assets/8754997/25668319/bd9a6f82-2ffc-11e7-9a06-81965ff9d69b.png)
![captura de tela de 2017-05-03 12-30-22](https://cloud.githubusercontent.com/assets/8754997/25668323/c0bd30dc-2ffc-11e7-9f13-3e666a0eba71.png)

**Comment by GabrielMGitHub** [comment]
The window should be showing this way.
![captura de tela de 2017-05-03 12-36-06](https://cloud.githubusercontent.com/assets/8754997/25668489/2a284458-2ffd-11e7-8381-24cf5063deef.png)

**Comment by danrabbit** [comment]
This dialog actually comes from GNOME and is not part of this code base. It is unfortunately an upstream issue and invalid for this repo
