### ISSUE TITLE
Bluetooth stopped working after quitting system settings.

### ISSUE THREAD

**Issue by clausbertels** [elementary/switchboard-plug-bluetooth#157]
## What Happened
Bluetooth stopped working after quitting system settings.

## Expected Behavior
I expect **only** system settings to close.

## Steps to Reproduce

1. Connect to bluetooth speaker
2. Open System Settings > Bluetooth
3. Press x to close window
4. Notice bluetooth connection dropped and is no longer shown in top panel.

## Platform Information
![Schermafdruk van 2020-12-26 17 30 33](https://user-images.githubusercontent.com/25482509/103155479-b3188480-47a0-11eb-8eb6-fb93570617b1.png)

**Comment by shawnc722** [comment]
I'm also having this issue on Jólnir. If you leave the bluetooth page in settings before closing it, it doesn't disconnect devices - the unexpected behaviour only happens when closing the bluetooth settings page itself.
