### ISSUE TITLE
Cannot find bluetooth-wizard

### ISSUE THREAD

**Issue by mblarsen** [elementary/switchboard-plug-bluetooth#19]
Nothing happens when clicking "Discover Devices.."

I ran `switchboard` from the commandline and repeated. This is what's in the log:

```
[WARNING 14:50:31.583131] MainView.vala:122: Failed to execute child process "bluetooth-wizard" (No such file or directory)
```

**Comment by cassidyjames** [comment]
@mblarsen are you on elementary OS Loki?

**Comment by cassidyjames** [comment]
I am seeing this on my relatively new Artful-based FrankenJuno install as well. It looks like bluetooth-wizard is [provided by unity-control-center](http://manpages.ubuntu.com/manpages/artful/man1/bluetooth-wizard.1.html).

**Comment by torikulhabib** [comment]
how about this source mr. group elementary
you redistribute blueman.
blueman working but dbus accepted confirmation not working.
i am sorry, maybe can help you.
https://github.com/blueman-project/blueman

**Comment by mblarsen** [comment]
@cassidyjames sorry for the late reply. Yes it is on Loki.
