### ISSUE TITLE
Bluetooth keeps dropping since update

### ISSUE THREAD

**Issue by ggrobi** [elementary/switchboard-plug-bluetooth#217]
I did an update on elementary OS 5.1.7 Hera and now the Bluetooth headphones keeps dropping after use 10-20 mins. I have several pairs, and it happens with all of them since the update. On the same laptop dual boot I go elementary OS 7 I don't have the problem. I haven't done any update on 7 because I don't want to cause the issue there too. I have away had a problem where Bluetooth sometimes interferes with the Wi-Fi intermittently.  That is fixed by turning Bluetooth off until it connects again, but this is rare.

**Comment by danirabbit** [comment]
Hey thanks for your report! At this time elementary OS 5 is no longer receiving updates from elementary. According to Ubuntu's documentation it's also no longer receiving updates from Canonical as of May last year. So I'm not sure where you might've gotten an update from there, but **OS 5 has reached the end of its life and it is no longer secure or recommended to run it. It will not continue to receive updates**

Closing as you reported this issue doesn't occur in OS 7 and OS 5 is no longer maintained
