### ISSUE TITLE
Crash if settings pressed while connecting sound device

### ISSUE THREAD

**Issue by jeremypw** [elementary/switchboard-plug-bluetooth#26]
* Set up bluetooth headphones as a device (check work OK).
* Disconnect and move headphones out of range.
* Press "Connect"
* While trying to connect press the settings button.
* After about a second the app crashes.

Issue experienced on Loki daily.

**Comment by peteruithoven** [comment]
On Juno beta (1) the ... (settings) button only appears after a successful connection has been made. So maybe this should be closed?

**Comment by leonardo-lemos** [comment]
Closing the issue as it's fixed in master.
