### ISSUE TITLE
Sort bluetooth devices with no name last

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-bluetooth#31]
I'm not sure about Android, but it looks like iOS doesn't even list these devices. I'm wondering if we should either also not show them or at least sort them below devices with names.

As it is, I have a big list of nameless devices sorted above and sometimes obscuring the devices I actually care about pairing with

![screenshot from 2018-03-06 12 56 05 2x](https://user-images.githubusercontent.com/7277719/37057918-c6ad79ec-213d-11e8-9fdc-1d1a1b857625.png)

**Comment by tintou** [comment]
Maybe we should just deprioritize them ?

**Comment by danrabbit** [comment]
Yeah I think at the least they should be sorted last, but I wonder if it's even valuable to show. I have no idea what all these devices are but if another major platform is just not even showing them, I wonder if it's important for us to

**Comment by cassidyjames** [comment]
Checking devices between my phone and computer… I see several unnamed devices on my computer, but a few devices on my phone that aren't listed on the computer. Is it possible getting the name timed out on the computer, or something?

I think before we know more, deprioritizing them (and maybe naming them something more friendly like "Unknown (MAC:ADDR:IN:DIM:LABEL)" would be useful?

**Comment by danrabbit** [comment]
In Slack, Corentin brought up the point that this can be useful for people developing embedded devices etc
