### ISSUE TITLE
Give option to disble bluetooth service altogether.

### ISSUE THREAD

**Issue by uncertainquark** [elementary/switchboard-plug-bluetooth#41]
I don't use Bluetooth and turned it off but it is re-enabled on every boot which is very annoying. Please give an option to safely disable the service altogether. The command line options didn't serve me well previously as I ran into issues.
![screenshot from 2018-05-03 15-56-46](https://user-images.githubusercontent.com/22585732/39571871-996404f8-4eea-11e8-8c94-9a0f67aa4146.png)

**Comment by danrabbit** [comment]
There is now a master switch for Bluetooth in master even when no devices are paired :)
