### ISSUE TITLE
appdata: stray U+200B (zero-width space) characters, breaks libappstream-glib

### ISSUE THREAD

**Issue by decathorpe** [elementary/switchboard-plug-bluetooth#47]
Any idea why those keep popping up?

**Comment by danrabbit** [comment]
Probably because the first one was copied from their website and then the others were copied from that one

**Comment by danrabbit** [comment]
Fixed in https://github.com/elementary/switchboard-plug-bluetooth/commit/a3a79fc9c5b1819ac0972cb605bc197db613cd4a
