### ISSUE TITLE
Discover devices dialog not adapting to number of found devices

### ISSUE THREAD

**Issue by thomorl** [elementary/switchboard-plug-bluetooth#55]
The "Discover Devices" dialog's list of all detected devices is not increasing or decreasing it's size when new devices are found/devices are lost. The new entries appear in the list, but can't be seen unless the window size is increased manually, making it look like the Bluetooth is not working.

Screenshots:

![window_default](https://user-images.githubusercontent.com/16212095/46662209-50665d00-cc17-11e8-9a00-b7fa03987a51.png)
**1** Default appearance (note the few visible pixels of the found device icon)

![window_resized](https://user-images.githubusercontent.com/16212095/46662210-50fef380-cc17-11e8-8788-583bf3a164b6.png)
**2** Manually resized

**Comment by peteruithoven** [comment]
The Bluetooth System Settings have had a total redesign, so this separate discovery window for example is no longer necessary. 
![bluetooth](https://user-images.githubusercontent.com/523210/46666776-dbb80200-cbc7-11e8-8173-568326c4ba57.png)

I'm afraid that this however won't be backported to Loki.

**Comment by peteruithoven** [comment]
I now see it has also been reported before: https://github.com/elementary/switchboard-plug-bluetooth/issues/15
