### ISSUE TITLE
Bluetooth don't work

### ISSUE THREAD

**Issue by henriquecouto** [elementary/switchboard-plug-bluetooth#61]
![captura de tela de 2018-10-26 13-14-39](https://user-images.githubusercontent.com/23243227/47579010-4172f080-d921-11e8-821c-59ffc731eb9c.png)

![captura de tela de 2018-10-26 13-15-00](https://user-images.githubusercontent.com/23243227/47579012-4172f080-d921-11e8-98f2-b49ca216fec8.png)

**Comment by peteruithoven** [comment]
There is not a lot anyone can do without a bit more info like, your bluetooth hardware, info on your computer.

**Comment by David-kobi** [comment]
please am experiencing the same issue on elementary os juno
