### ISSUE TITLE
Use disabled icon when bluetooth is disabled

### ISSUE THREAD

**Issue by danrabbit** [elementary/switchboard-plug-bluetooth#62]
![screenshot from 2018-11-01 13 51 28 2x](https://user-images.githubusercontent.com/7277719/47879217-4e8a5680-dddd-11e8-93b5-dcac2b2f0134.png)

**Comment by joshnroy** [comment]
Hi DanRabit (and anyone else this may pertain to).

I'm a college student and haven't solved many bugs on open source projects before, but found elementary recently, really like it, and would like to try to contribute. I'll try fixing this and see if it works!

Thanks,
Josh

**Comment by joshnroy** [comment]
Update: I found the place to change the code, and can now change the icon when bluetooth is on/off. I'm not sure if there's a general list of icons that includes the one you show in your screenshot? I'll look for it

**Comment by joshnroy** [comment]
Just pulled the new icon set, and it uses the correct icons now

**Comment by danrabbit** [comment]
hey @joshnroy sorry, I submitted a fix for this quite a while ago and forgot to link the issue. I've fixed the link, and the PR has more information about the missing icon and why it's not merged yet

**Comment by joshnroy** [comment]
Sounds good. Thanks @danrabbit!
