### ISSUE TITLE
Apple wireless keyboard can't connect.

### ISSUE THREAD

**Issue by Qmo37** [elementary/switchboard-plug-bluetooth#74]
Before installed elementary OS, I could connected my apple wireless keyboard to my iMac 2010 mid.
but after I installed OS, I couldn't connect to my iMac, sorry I'm new to Linux.
BTW I've tried this https://support.system76.com/articles/bluetooth/

**Comment by Qmo37** [comment]
Thanks for your suggestion.
Somehow, I connected successfully yesterday in pairing mode like you said, but the keyboard didn't work normally, only some parts of keyboard could type and only came out with numbers. No matter how I disconnect and reconnect, it still only numbers.

**Comment by danrabbit** [comment]
Closing since this sounds like some kind of hardware failure
